---
# Source: argocd/charts/argo-cd/templates/argocd-server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: argocd-server
  namespace: "argocd"
  annotations:
    iam.gke.io/gcp-service-account: "argocd@emp-jace-a850.iam.gserviceaccount.com"
  labels:
    helm.sh/chart: argo-cd-6.7.2
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.10.3"
