---
# Source: tailscale-operator/charts/tailscale-operator/templates/proxy-rbac.yaml
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxies
  namespace: tailscale-operator
---
# Source: tailscale-operator/charts/tailscale-operator/templates/proxy-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxies
  namespace: tailscale-operator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
# Source: tailscale-operator/charts/tailscale-operator/templates/proxy-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxies
  namespace: tailscale-operator
subjects:
- kind: ServiceAccount
  name: proxies
  namespace: tailscale-operator
roleRef:
  kind: Role
  name: proxies
  apiGroup: rbac.authorization.k8s.io
