---
apiVersion: v2
name: tailscale-operator
version: 0.0.0

dependencies:
- name: tailscale-operator
  version: 1.60.1
  # Docs available: https://github.com/tailscale/tailscale/tree/main/cmd/k8s-operator/deploy
  repository: https://pkgs.tailscale.com/helmcharts
